"""Added last check in to engine

Revision ID: 33b817d6453b
Revises: b60ccf4d817c
Create Date: 2019-02-17 23:24:13.028000

"""
from alembic import op
import sqlalchemy as sa
import ScoringEngine.core.db.customTypes


# revision identifiers, used by Alembic.
revision = '33b817d6453b'
down_revision = 'b60ccf4d817c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engines', sa.Column('last_checkin', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engines', 'last_checkin')
    # ### end Alembic commands ###
