"""Added usersettings table

Revision ID: 4a07ac822a75
Revises: e7e4493ff4ac
Create Date: 2018-09-29 21:26:12.679000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a07ac822a75'
down_revision = 'e7e4493ff4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersettings',
    sa.Column('userid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userid', 'key')
    )
    op.create_index(op.f('ix_usersettings_key'), 'usersettings', ['key'], unique=False)
    op.create_index(op.f('ix_usersettings_userid'), 'usersettings', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersettings_userid'), table_name='usersettings')
    op.drop_index(op.f('ix_usersettings_key'), table_name='usersettings')
    op.drop_table('usersettings')
    # ### end Alembic commands ###
