"""Added engine_id to server

Revision ID: 85921a98562e
Revises: 33b817d6453b
Create Date: 2019-02-18 15:11:53.424000

"""
from alembic import op
import sqlalchemy as sa
import ScoringEngine.core.db.customTypes

from sqlalchemy import orm
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


# revision identifiers, used by Alembic.
revision = '85921a98562e'
down_revision = '33b817d6453b'
branch_labels = None
depends_on = None


class Server(Base):
    __tablename__ = 'servers'

    id = sa.Column(sa.Integer, primary_key=True)
    engine_id = sa.Column(sa.Integer, sa.ForeignKey("engines.id"))


class Engine(Base):
    __tablename__ = 'engines'

    id = sa.Column(sa.Integer, primary_key=True)


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('engine_id', sa.Integer(), nullable=True))
    if 'sqlite' not in op.get_context().connection.engine.url.drivername:
        op.create_foreign_key(None, 'servers', 'engines', ['engine_id'], ['id'])
    # ### end Alembic commands ###

    for server in session.query(Server):
        server.engine_id = 0

    session.commit()
    if 'sqlite' not in op.get_context().connection.engine.url.drivername:
        op.alter_column('servers', 'engine_id', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_column('servers', 'engine_id')
    # ### end Alembic commands ###
