"""Added engines

Revision ID: b60ccf4d817c
Revises: d64a8087c1fc
Create Date: 2019-02-16 23:27:23.800000

"""
from alembic import op
import sqlalchemy as sa
import ScoringEngine.core.db.customTypes


# revision identifiers, used by Alembic.
revision = 'b60ccf4d817c'
down_revision = 'd64a8087c1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engines_id'), 'engines', ['id'], unique=True)
    op.add_column(u'scoreevents', sa.Column('engineid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_scoreevents_engineid'), 'scoreevents', ['engineid'], unique=False)
    op.create_foreign_key(None, 'scoreevents', 'engines', ['engineid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scoreevents', type_='foreignkey')
    op.drop_index(op.f('ix_scoreevents_engineid'), table_name='scoreevents')
    op.drop_column(u'scoreevents', 'engineid')
    op.drop_index(op.f('ix_engines_id'), table_name='engines')
    op.drop_table('engines')
    # ### end Alembic commands ###
