variables:
  CI_REGISTRY_IMAGE: 'registry.thebmw.com/norserage/scoring'

dev_docker_build:
  except:
    - master
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN registry.thebmw.com
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-web" -f Dockerfile-web .
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-score" -f Dockerfile-score .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-web"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME-score"
  tags:
    - docker-build

release_docker_build:
  only:
    - master
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN registry.thebmw.com
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:web" -f Dockerfile-web .
    - docker build --pull -t "$CI_REGISTRY_IMAGE:score" -f Dockerfile-score .
    - docker push "$CI_REGISTRY_IMAGE:web"
    - docker push "$CI_REGISTRY_IMAGE:score"
  tags:
    - docker-build

