FROM python:2

RUN apt-get update && \
    apt-get install -y \
    dnsutils \
    && \
    rm -rf /var/lib/apt/lists/*

COPY ScoringEngine/requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt

COPY ScoringEngine /

ARG BRANCH=unknown
ARG BUILD=non-ci-build

ENV CI_BRANCH=$BRANCH \
    CI_BUILD=$BUILD

CMD ["/runner.sh", "score"]