FROM python:2

RUN apt-get update && \
    apt-get install -y \
    dnsutils \
    && \
    rm -rf /var/lib/apt/lists/*

COPY ScoringEngine /

RUN pip install --no-cache-dir -r /requirements.txt

CMD ["/runner.sh", "score"]