FROM arm32v7/python:2

COPY /usr/bin/qemu-arm-static /usr/bin/qemu-arm-static

RUN apt-get update && \
    apt-get install -y \
    dnsutils \
    && \
    rm -rf /var/lib/apt/lists/*

COPY ScoringEngine/requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt

ARG BRANCH=unknown
ARG BUILD=non-ci-build

COPY ScoringEngine /

ENV CI_BRANCH=$BRANCH \
    CI_BUILD=$BUILD

CMD ["/runner.sh", "score"]